### ISSUE TITLE
Vendor directory outdated?

### ISSUE THREAD

**Issue by fabiob** [compose/bach#13]
Hi. I'm trying to author a Homebrew recipe for `bach`. I was asked to make it build from source (see: Homebrew/homebrew-core#14314). However, I could not make it build with the current `vendor` directory.

Running `go build` results in the following failures:

```
# github.com/compose/bach/cmd
cmd/deprovision.go:35: c.DeprovisionDeploymentJSON undefined (type *composeapi.Client has no field or method DeprovisionDeploymentJSON)
cmd/deprovision.go:39: c.DeprovisionDeployment undefined (type *composeapi.Client has no field or method DeprovisionDeployment)
```

If I remove the `vendor` directory and perform a `go get ./...`, it works.

Am I missing something?

**Comment by atomicules** [comment]
See: https://github.com/compose/bach/pull/8
