### ISSUE TITLE
undefined: PositionalArgs on `go get`

### ISSUE THREAD

**Issue by kosfar** [compose/bach#16]
Hi,
I am trying to `go get -u github.com/compose/bach` but I get the following error:
```
# github.com/compose/bach/vendor/github.com/spf13/cobra
src/github.com/compose/bach/vendor/github.com/spf13/cobra/command.go:58:7: undefined: PositionalArgs
```

Same happens if I `go install` or `go build` inside a cloned repo. Am I missing something?

I am on MacOS Sierra and installed go via brew:
```
$ go version
go version go1.9.1 darwin/amd64
```
BR,
Kostis

**Comment by codepope** [comment]
There seems to have been a change in the dependencies which made things got a little odd in the vendor directory. I've done a fixup on that so please, have another try.

Dj

**Comment by kosfar** [comment]
Thank you, it works now!
