### ISSUE TITLE
Suggestion:  "created_at" in deployments output

### ISSUE THREAD

**Issue by drpalaric** [compose/bach#7]
Just suggesting that "created_at" is included the output of `bach deployments` without flags set. There are times when two deployments with the same name are listed in the output for some reason - I don't know if this is an issue in the API or what. At the same time, the erroneous deployment is not shown in the Compose console, but only then accessing the API.  If "created_at" was included, you wouldn't have to add `--json` or `--raw` to see that one of them is an older deployment so that you could deprovision it. See image:

<img width="327" alt="screen shot 2017-05-17 at 6 14 35 pm" src="https://cloud.githubusercontent.com/assets/6264696/26182518/9f3ff14c-3b2d-11e7-84a6-313eb5ebfa05.png">

**Comment by codepope** [comment]
There is no bug; the second entry is a child deployment for the shard. The API currently returns it though it may not in future.

secondly, there already is a --long flag for deployments to list more information including created date, and web ui link.

note the created date of both would be very close if not the same.
